name1 = input("enter name 1 :")
age1 = input("enter age 1 :")
# name2 = input("enter name 2 :")
# age2 = input("enter age 2 :")
# name3 = input("enter name 3 :")
# age3 = input("enter age 3 :")
# print(f"{name1:^20}|{age1:^5}")
# print(f"{name2:^20}|{age2:^5}")
# print(f"{name3:^20}|{age3:^5}")
print(name1.center(20)+'|'+age1.center(5))
print(name2.center(20)+'|'+age2.center(5))
print(name3.center(20)+'|'+age3.center(5))
